### PR TITLE
Some fixes

### PR DESCRIPTION
**Pull request by hanzala1234**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/825fca9eab254a20d383fd0bf710c7618eccf6ef/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/322460a9ebe2f6d62c6dba286727f9a01896e295/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/6f7bf826a196d4e7f1f96e9a3b00292077466052/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Validation Successful

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
