### PR TITLE
Use test cluster to validate changes

### PR DESCRIPTION
**Pull request by hanzala1234**

### CODE REVIEW

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/4a2ff67af17531d178a0f9dc6f299d26acc41997/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit//checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/156827cb3bf843bf1267e1de74732be96cb4010c/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/405383038f4c18b4df7e1ef60ef3e5893dc76330/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/835e88f7d6d2c7385d6cd3e6c420b0e4a023d0a0/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Validation Successful

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/f742a75f8bddaf2fa709a6eee5f08094dfd1bfaa/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/100d730c8b23acf815f61d29d9fade52a3899718/checks) has Failed!

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
