### PR TITLE
Render .Values.deployment.volumes  as template

### PR DESCRIPTION
**Pull request by Hallonbat**
In order to be able to mount a configMap,
whose name includes the application name,
as a volume render the volumes array with the tpl function

### CODE REVIEW

**Comment by stakater-user** [comment]
@Hallonbat [Build 1](https://jenkins-delivery.stakater.com/job/Stakater-Charts/job/application/job/PR-50/1/) has Failed!

**Comment by stakater-user** [comment]
@Hallonbat [Build 2](https://jenkins-delivery.stakater.com/job/Stakater-Charts/job/application/job/PR-50/2/) has Failed!

**Comment by stakater-user** [comment]
@Hallonbat [Build 3](https://jenkins-delivery.stakater.com/job/Stakater-Charts/job/application/job/PR-50/3/) has Failed!

**Comment by stakater-user** [comment]
@Hallonbat [Build 4](https://jenkins-delivery.stakater.com/job/Stakater-Charts/job/application/job/PR-50/4/) has Failed!

**Comment by ahmedwaleedmalik** [comment]
@Hallonbat Can you please merge the latest master in your branch ?

**Comment by Hallonbat** [comment]
@ahmedwaleedmalik I merged the latest master Yesterday but the checks are still failing. Is there a problem with my changes or the checks?

**Comment by rasheedamir** [comment]
@Hallonbat can you plz get the latest master once again? for forked repos it was broken

**Comment by stakater-user** [comment]
@Hallonbat Validation Successful

**Review by rasheedamir — APPROVED** [review]

**Pull request merged**
