### PR TITLE
Add endpoint moinitor

### PR DESCRIPTION
**Pull request by rasheedamir**
add endpoint monitor

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Chart: application Dry Run successful

**Comment by stakater-user** [comment]
@rasheedamir Chart: application Dry Run successful

**Comment by stakater-user** [comment]
@rasheedamir Chart: application Dry Run successful

**Comment by stakater-user** [comment]
@rasheedamir Chart: application Dry Run successful

**Comment by stakater-user** [comment]
@rasheedamir Chart: application Dry Run successful

**Review by usamaahmadkhan — APPROVED** [review]

**Pull request merged**
