### PR TITLE
Add dns config

### PR DESCRIPTION
**Pull request by hanzala1234**

### CODE REVIEW

**Comment by stakater-user** [comment]
@rasheedamir Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/20af44c370c0a76dab7e8bcd065edb9885ec9a8c/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/20af44c370c0a76dab7e8bcd065edb9885ec9a8c/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/ed8c62bd689e5c65373a7b2b93baa6127a1110ba/checks) has Failed!

**Comment by stakater-user** [comment]
@hanzala1234 Validation Successful

**Review by bilalbokharee — APPROVED** [review]

**Comment by stakater-user** [comment]
@hanzala1234 Yikes! You better fix it before anyone else finds out! [Build](https://github.com/stakater-charts/application/commit/11dea0f74660badbaeb063213110c8c33168dc8e/checks) has Failed!

**Review by bilalbokharee — APPROVED** [review]

**Pull request merged**
