### PR TITLE
Add volume mounts persistence and fix labels

### PR DESCRIPTION
**Pull request by kahootali**
This PR
- removes default values for rolling update as cant set strategy to recreate due to it
- changes pod label as application label is part of chart now
- adds values for mount pvc and path in case persistence is true

### CODE REVIEW

**Comment by stakater-user** [comment]
@kahootali Chart: application Dry Run successful

**Comment by rasheedamir** [comment]
@kahootali update readme as well

**Comment by stakater-user** [comment]
@kahootali Chart: application Dry Run successful

**Comment by stakater-user** [comment]
@kahootali Chart: application Dry Run successful

**Review by ahmedwaleedmalik — APPROVED** [review]
LGTM

**Pull request merged**
